### ISSUE TITLE
Swagger JSON not working

### ISSUE THREAD

**Issue by sorenhansendk** [wobsoriano/elysia-autoroutes#7]
I'm not able to use the Swagger module: https://github.com/elysiajs/elysia-swagger

When I request the JSON `/swagger/json` it return this error in my console.

<pre>
56 |                 registerSchemaPath({
57 |                     schema,
58 |                     hook: route.hooks,
59 |                     method: route.method,
60 |                     path: route.path,
61 |                     models: app.definitions.type,
                                ^
TypeError: undefined is not an object (evaluating 'app.definitions.type')
      at /Users/sorenhansen/Code/vivens-io/node_modules/@elysiajs/swagger/dist/index.js:61:28
      at forEach (:1:20)
      at /Users/sorenhansen/Code/vivens-io/node_modules/@elysiajs/swagger/dist/index.js:55:12
GET - /swagger/json failed
</pre>

**Comment by sorenhansendk** [comment]
It works! I forgot to align my versions of the packages:

- `elysia`
- `elysia-autoroutes`
- `@elysiajs/swagger`
